runtime: nodejs20
service: tech-inspect
handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
